import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@lianqq/ui/globals.css"
import TechBitHeader from "@/components/layout/techbit-header";
import TechBitFooter from "@/components/layout/techbit-footer";
import TechBitMain from "@/components/layout/techbit-main";
import ThemeProvider from '@/provider/theme-provider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TechBitHeader />
          <TechBitMain>
            {children}
          </TechBitMain>
          <TechBitFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
